import type { DiaryRow, FragranceListType } from '$lib/types/diary'

export const MOCK_DIARY: Record<FragranceListType, DiaryRow[]> = {
  to_try: [
    {
      id: 1,
      fragranceId: 1,
      brand: "Maison d'Aura",
      fragrance: 'Sable Doré',
      notes: ['iris', 'amber', 'skin'],
      rating: 0,
      statusLabel: 'Queued',
      statusTone: 'neutral',
      isOwned: false,
      isTried: false,
      isLiked: null,
      isRecommendation: false,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
    {
      id: 2,
      fragranceId: 2,
      brand: 'Lumen Olfactive',
      fragrance: 'Verre Vert',
      notes: ['galbanum', 'violet leaf', 'moss'],
      rating: 0,
      statusLabel: 'Sample',
      statusTone: 'accent',
      isOwned: true,
      isTried: false,
      isLiked: null,
      isRecommendation: false,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
  ],
  liked: [
    {
      id: 3,
      fragranceId: 3,
      brand: 'Atelier Nord',
      fragrance: 'Birch Silence',
      notes: ['birch', 'smoke', 'cedar'],
      rating: 5,
      statusLabel: 'Signature',
      statusTone: 'success',
      isOwned: true,
      isTried: true,
      isLiked: true,
      isRecommendation: false,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
  ],
  disliked: [
    {
      id: 4,
      fragranceId: 4,
      brand: 'Pulse Lab',
      fragrance: 'Neon Sugar',
      notes: ['caramel', 'synthetic musk'],
      rating: 2,
      statusLabel: 'Too sweet',
      statusTone: 'warning',
      isOwned: false,
      isTried: true,
      isLiked: false,
      isRecommendation: false,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
  ],
  owned: [
    {
      id: 5,
      fragranceId: 5,
      brand: 'Oryxel Editions',
      fragrance: 'Noir Papyrus',
      notes: ['papyrus', 'black tea', 'ink'],
      rating: 4,
      statusLabel: 'Collection',
      statusTone: 'accent',
      isOwned: true,
      isTried: true,
      isLiked: true,
      isRecommendation: false,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
  ],
}
