export type FamilyDefinition = {
  family: string
  color: string
  keywords: string[]
  /** Per-locale display name. Falls back to `family` if locale not found. */
  translations?: Record<string, string>
}

/** Resolve the display name for a family in a given locale. */
export function familyDisplayName(family: FamilyDefinition, locale: string): string {
  return family.translations?.[locale] ?? family.translations?.['en'] ?? family.family
}

const FAMILY_DEFS: FamilyDefinition[] = [
  {
    family: 'citrus',
    color: '#FFB347',
    keywords: [
      // EN
      'bergamot',
      'lemon',
      'lime',
      'orange',
      'grapefruit',
      'mandarin',
      'tangerine',
      'yuzu',
      'citrus',
      'citron',
      'kumquat',
      'neroli',
      'petitgrain',
      'clementine',
      'blood orange',
      'pomelo',
      'satsuma',
      'nectarine',
      'lemon verbena',
      'verbena',
      'melissa',
      'lemon balm',
      'lemon zest',
      'orange zest',
      'citrus peel',
      'orange blossom',
      'orange flower',
      'calabrian',
      'amalfi',
      'sicilian',
      'cedrat',
      'bigarade',
      'combava',
      'sudachi',
      'citronella',
      'litsea cubeba',
      'petitgrain bigarade',
      'hesperides',
      'hesperidic',
      // RU
      'бергамот',
      'лимон',
      'апельсин',
      'мандарин',
      'грейпфрут',
      'юзу',
      'лайм',
      'помело',
      'клементин',
      'цитрон',
      'цитрус',
      'вербена',
      'мелисса',
      'лимонная вербена',
      'нероли',
      'цедрат',
      'кожура цитруса',
      'цветок апельсина',
      'цитронелла',
    ],
  },
  {
    family: 'floral',
    color: '#FF69B4',
    keywords: [
      // EN
      'rose',
      'jasmine',
      'lavender',
      'violet',
      'lily',
      'iris',
      'peony',
      'magnolia',
      'gardenia',
      'tuberose',
      'ylang',
      'osmanthus',
      'freesia',
      'carnation',
      'geranium',
      'heliotrope',
      'mimosa',
      'narcissus',
      'orris',
      'cherry blossom',
      'lotus',
      'water lily',
      'wisteria',
      'honeysuckle',
      'elderflower',
      'lily of the valley',
      'muguet',
      'tiare',
      'frangipani',
      'hyacinth',
      'dahlia',
      'edelweiss',
      'acacia',
      'immortelle',
      'everlasting',
      'peach blossom',
      'rose water',
      'rose absolute',
      'sambac',
      'grandiflorum',
      'heliotropin',
      'floral',
      'flower',
      'blossom',
      'bloom',
      'wallflower',
      'sweet pea',
      'clary sage',
      'jonquil',
      'chrysanthemum',
      'lilac',
      'hawthorn',
      'blackcurrant bud',
      'cassis bud',
      'boronia',
      'calycanthus',
      // RU
      'роза',
      'жасмин',
      'лаванда',
      'фиалка',
      'лилия',
      'ирис',
      'пион',
      'магнолия',
      'гардения',
      'тубероза',
      'иланг',
      'османтус',
      'фрезия',
      'гвоздика',
      'герань',
      'гелиотроп',
      'мимоза',
      'нарцисс',
      'оррис',
      'цветок вишни',
      'лотос',
      'кувшинка',
      'глициния',
      'жимолость',
      'бузина',
      'ландыш',
      'тиаре',
      'плюмерия',
      'гиацинт',
      'хризантема',
      'сирень',
      'боярышник',
      'цветочный',
      'цветы',
      'цветок',
      'альтоцветный',
    ],
  },
  {
    family: 'woody',
    color: '#8B4513',
    keywords: [
      // EN
      'cedar',
      'sandalwood',
      'vetiver',
      'oud',
      'agarwood',
      'guaiac',
      'patchouli',
      'oakmoss',
      'birch',
      'pine',
      'fir',
      'rosewood',
      'teak',
      'ebony',
      'mahogany',
      'bark',
      'driftwood',
      'wood',
      'woody',
      'timber',
      'amyris',
      'elemi',
      'frankincense',
      'incense',
      'myrrh',
      'olibanum',
      'benzoin',
      'labdanum',
      'cypress',
      'juniper',
      'spruce',
      'fir needle',
      'pine needle',
      'gaiac wood',
      'clearwood',
      'javanol',
      'timberol',
      'sandalore',
      'iso e super' /* already musky but */,
      'cashmeran',
      'cedarwood',
      'hinoki',
      'cryptomeria',
      'maple wood',
      'elm',
      'styrax',
      'balsam',
      'peru balsam',
      'tolu balsam',
      'tree moss',
      'oakwood',
      'poplar',
      'bamboo',
      'driftwood',
      'woody amber',
      // RU
      'кедр',
      'сандал',
      'ветивер',
      'уд',
      'пачули',
      'дубовый мох',
      'береза',
      'сосна',
      'дерево',
      'кора',
      'ладан',
      'мирра',
      'смирна',
      'бензоин',
      'лабданум',
      'смола',
      'можжевельник',
      'кипарис',
      'ель',
      'пихта',
      'древесный',
      'древесина',
      'франкинсенс',
      'элеми',
      'амирис',
      'тик',
      'эбен',
      'гваяк',
      'хиноки',
    ],
  },
  {
    family: 'spicy',
    color: '#D2691E',
    keywords: [
      // EN
      'pepper',
      'cardamom',
      'cinnamon',
      'clove',
      'nutmeg',
      'ginger',
      'saffron',
      'cumin',
      'coriander',
      'star anise',
      'pink pepper',
      'black pepper',
      'red pepper',
      'white pepper',
      'allspice',
      'mace',
      'bay leaf',
      'bay rum',
      'fenugreek',
      'turmeric',
      'galangal',
      'wasabi',
      'horseradish',
      'chili',
      'cayenne',
      'paprika',
      'szechuan',
      'anise',
      'fennel',
      'caraway',
      'dill seed',
      'spice',
      'spicy',
      'artemisia',
      'wormwood',
      'absinthe',
      'tarragon',
      'clove bud',
      'ginger root',
      'dried cloves',
      'pepper berry',
      'long pepper',
      // RU
      'перец',
      'кардамон',
      'корица',
      'гвоздика',
      'мускатный',
      'имбирь',
      'шафран',
      'тмин',
      'кориандр',
      'бадьян',
      'розовый перец',
      'черный перец',
      'красный перец',
      'анис',
      'фенхель',
      'лавр',
      'куркума',
      'паприка',
      'перец чили',
      'перец кайенский',
      'специи',
      'пряности',
      'пряный',
      'полынь',
      'абсент',
      'эстрагон',
    ],
  },
  {
    family: 'musky',
    color: '#DDA0DD',
    keywords: [
      // EN — musks
      'musk',
      'ambroxan',
      'ambergris',
      'amber',
      'civet',
      'castoreum',
      'galaxolide',
      'habanolide',
      'ethylene brassylate',
      'iso e super',
      'clean musk',
      'white musk',
      'skin musk',
      'powdery musk',
      'musks',
      'ambrette',
      'muscone',
      'exaltolide',
      'hedione',
      // EN — warm/oriental/gourmand
      'vanilla',
      'tonka bean',
      'tonka',
      'coumarin',
      'beeswax',
      'lactone',
      'lactonic',
      'honey',
      'honeycomb',
      'sugar',
      'caramel',
      'praline',
      'chocolate',
      'cocoa',
      'cacao',
      'coffee',
      'espresso',
      'almond',
      'marzipan',
      'coconut',
      'nougat',
      'maple',
      'rum',
      'bourbon',
      'whiskey',
      'cognac',
      'powder',
      'powdery',
      'talc',
      'soft',
      'gourmand',
      'sweet',
      'warm',
      'sensual',
      // RU
      'мускус',
      'амбра',
      'амброксан',
      'цивет',
      'ваниль',
      'тонка',
      'кумарин',
      'пчелиный воск',
      'мёд',
      'сахар',
      'карамель',
      'шоколад',
      'кофе',
      'миндаль',
      'кокос',
      'пралине',
      'нуга',
      'ром',
      'пудровый',
      'пудра',
      'тальк',
      'белый мускус',
      'чистый мускус',
      'мускусный',
      'сладкий',
      'теплый',
    ],
  },
  {
    family: 'green',
    color: '#7CB342',
    keywords: [
      // EN
      'basil',
      'mint',
      'rosemary',
      'thyme',
      'sage',
      'tarragon',
      'tea',
      'fig',
      'tomato leaf',
      'violet leaf',
      'galbanum',
      'grass',
      'green',
      'herb',
      'herbal',
      'leaf',
      'leaves',
      'vine',
      'nettle',
      'veronica',
      'green tea',
      'matcha',
      'cut grass',
      'hay',
      'seaweed',
      'algae',
      'kelp',
      'moss',
      'vetiver leaf',
      'cannabis',
      'hemp',
      'artichoke',
      'lovage',
      'parsley',
      'hyssop',
      'marjoram',
      'oregano',
      'green accord',
      'green note',
      'stem',
      'bud',
      'shoot',
      // RU
      'базилик',
      'мята',
      'розмарин',
      'тимьян',
      'шалфей',
      'чай',
      'инжир',
      'трава',
      'зеленый',
      'лист',
      'листья',
      'зелень',
      'зеленый чай',
      'матча',
      'камыш',
      'водоросли',
      'мох',
      'крапива',
      'петрушка',
      'мята перечная',
      'зеленые ноты',
      'побег',
      'бутон',
      'стебель',
    ],
  },
  {
    family: 'fresh',
    color: '#5DADE2',
    keywords: [
      // EN — aquatics/marine
      'aquatic',
      'marine',
      'sea',
      'ocean',
      'water',
      'ozone',
      'aldehydic',
      'ozonic',
      'rain',
      'air',
      'breeze',
      'fresh',
      'marine accord',
      'sea spray',
      'sea salt',
      'salt',
      'mineral',
      'chalk',
      'snow',
      'ice',
      'frost',
      'arctic',
      'glacial',
      'calone',
      'ambrette seed',
      'crystal',
      'clean',
      // EN — fruits (light, watery)
      'apple',
      'green apple',
      'pear',
      'peach',
      'apricot',
      'plum',
      'watermelon',
      'melon',
      'lychee',
      'rhubarb',
      'raspberry',
      'strawberry',
      'blackberry',
      'blueberry',
      'currant',
      'cassis',
      'berry',
      'red berries',
      'white peach',
      'passion fruit',
      'guava',
      'mango',
      'pineapple',
      'kiwi',
      'fig water',
      // RU
      'морская',
      'океан',
      'вода',
      'озон',
      'свежий',
      'огурец',
      'морской',
      'морская соль',
      'соль',
      'снег',
      'лёд',
      'минеральный',
      'чистый',
      'яблоко',
      'груша',
      'персик',
      'абрикос',
      'арбуз',
      'дыня',
      'ревень',
      'личи',
      'малина',
      'клубника',
      'ежевика',
      'черника',
      'смородина',
      'ягода',
    ],
  },
  {
    family: 'leather',
    color: '#5D4037',
    keywords: [
      // EN
      'leather',
      'tobacco',
      'suede',
      'smoke',
      'tar',
      'birch tar',
      'chamois',
      'ink',
      'rubber',
      'gasoline',
      'petrol',
      'gunpowder',
      'metal',
      'iron',
      'mushroom',
      'truffle',
      'earth',
      'dirt',
      'soil',
      'vetiver root',
      'moss',
      'papyrus',
      'castoreum',
      'tobacco leaf',
      'virginia tobacco',
      'pipe tobacco',
      'oud leather',
      'smoky',
      'dark',
      'animalic',
      'earthy',
      // RU
      'кожа',
      'табак',
      'замша',
      'дым',
      'деготь',
      'чернила',
      'резина',
      'бензин',
      'металл',
      'железо',
      'грибы',
      'трюфель',
      'земля',
      'почва',
      'табачный',
      'дымный',
      'животный',
      'землистый',
      'кожаный',
    ],
  },
]

export function detectFamily(
  note: string,
  families: FamilyDefinition[] = FAMILY_DEFS,
): { family: string; color: string } {
  const lower = note.toLowerCase()

  for (const familyEntry of families) {
    if (familyEntry.keywords.some((kw) => lower.includes(kw))) {
      return { family: familyEntry.family, color: familyEntry.color }
    }
  }

  return { family: 'other', color: '#9E9E9E' }
}
