type FamilyDefinition = {
  family: string
  color: string
  keywords: string[]
}

const FAMILY_DEFS: FamilyDefinition[] = [
  {
    family: 'citrus',
    color: '#FFB347',
    keywords: [
      'bergamot',
      'lemon',
      'lime',
      'orange',
      'grapefruit',
      'mandarin',
      'tangerine',
      'yuzu',
      'citrus',
      'citron',
      'kumquat',
      'neroli',
      'petitgrain',
      'бергамот',
      'лимон',
      'апельсин',
      'мандарин',
      'грейпфрут',
      'юзу',
    ],
  },
  {
    family: 'floral',
    color: '#FF69B4',
    keywords: [
      'rose',
      'jasmine',
      'lavender',
      'violet',
      'lily',
      'iris',
      'peony',
      'magnolia',
      'gardenia',
      'tuberose',
      'ylang',
      'osmanthus',
      'freesia',
      'carnation',
      'geranium',
      'heliotrope',
      'mimosa',
      'narcissus',
      'orris',
      'роза',
      'жасмин',
      'лаванда',
      'фиалка',
      'лилия',
      'ирис',
      'пион',
      'магнолия',
      'гардения',
      'тубероза',
      'иланг',
    ],
  },
  {
    family: 'woody',
    color: '#8B4513',
    keywords: [
      'cedar',
      'sandalwood',
      'vetiver',
      'oud',
      'agarwood',
      'guaiac',
      'patchouli',
      'oakmoss',
      'birch',
      'pine',
      'fir',
      'rosewood',
      'кедр',
      'сандал',
      'ветивер',
      'уд',
      'пачули',
      'дубовый мох',
      'береза',
      'сосна',
    ],
  },
  {
    family: 'spicy',
    color: '#D2691E',
    keywords: [
      'pepper',
      'cardamom',
      'cinnamon',
      'clove',
      'nutmeg',
      'ginger',
      'saffron',
      'cumin',
      'coriander',
      'star anise',
      'pink pepper',
      'black pepper',
      'перец',
      'кардамон',
      'корица',
      'гвоздика',
      'мускатный',
      'имбирь',
      'шафран',
      'тмин',
      'кориандр',
    ],
  },
  {
    family: 'fresh',
    color: '#5DADE2',
    keywords: [
      'aquatic',
      'marine',
      'sea',
      'ocean',
      'water',
      'ozone',
      'aldehydic',
      'green',
      'grass',
      'cucumber',
      'rain',
      'air',
      'breeze',
      'fresh',
      'морская',
      'океан',
      'вода',
      'озон',
      'свежий',
      'огурец',
      'трава',
    ],
  },
  {
    family: 'musky',
    color: '#DDA0DD',
    keywords: [
      'musk',
      'ambroxan',
      'ambergris',
      'amber',
      'civet',
      'castoreum',
      'iso e super',
      'galaxolide',
      'habanolide',
      'мускус',
      'амбра',
      'амброксан',
    ],
  },
  {
    family: 'green',
    color: '#7CB342',
    keywords: [
      'basil',
      'mint',
      'rosemary',
      'thyme',
      'sage',
      'tarragon',
      'tea',
      'fig',
      'tomato leaf',
      'violet leaf',
      'galbanum',
      'базилик',
      'мята',
      'розмарин',
      'тимьян',
      'шалфей',
      'эстрагон',
      'чай',
      'инжир',
    ],
  },
  {
    family: 'leather',
    color: '#5D4037',
    keywords: ['leather', 'tobacco', 'suede', 'smoke', 'tar', 'birch tar', 'кожа', 'табак', 'замша', 'дым'],
  },
]

export function detectFamily(note: string): { family: string; color: string } {
  const lower = note.toLowerCase()

  for (const familyEntry of FAMILY_DEFS) {
    if (familyEntry.keywords.some((kw) => lower.includes(kw))) {
      return { family: familyEntry.family, color: familyEntry.color }
    }
  }

  return { family: 'other', color: '#9E9E9E' }
}
