import type { DiaryRow, FragranceListType } from '$lib/types/diary'

export const MOCK_DIARY: Record<FragranceListType, DiaryRow[]> = {
  to_try: [
    {
      id: 1,
      fragranceId: 1,
      brand: "Maison d'Aura",
      fragrance: 'Sable Doré',
      notes: ['iris', 'amber', 'skin'],
      rating: 0,
      agentComment: '',
      userComment: null,
      isOwned: false,
      isTried: false,
      isLiked: false,
      isDisliked: false,
      isRecommendation: true,
      season: null,
      timeOfDay: null,
      gender: null,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
    {
      id: 2,
      fragranceId: 2,
      brand: 'Lumen Olfactive',
      fragrance: 'Verre Vert',
      notes: ['galbanum', 'violet leaf', 'moss'],
      rating: 0,
      agentComment: '',
      userComment: null,
      isOwned: true,
      isTried: false,
      isLiked: false,
      isDisliked: false,
      isRecommendation: false,
      season: null,
      timeOfDay: null,
      gender: null,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
  ],
  neutral: [],
  liked: [
    {
      id: 3,
      fragranceId: 3,
      brand: 'Atelier Nord',
      fragrance: 'Birch Silence',
      notes: ['birch', 'smoke', 'cedar'],
      rating: 5,
      agentComment: '',
      userComment: 'Signature',
      isOwned: true,
      isTried: true,
      isLiked: true,
      isDisliked: false,
      isRecommendation: false,
      season: null,
      timeOfDay: null,
      gender: null,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
  ],
  disliked: [
    {
      id: 4,
      fragranceId: 4,
      brand: 'Pulse Lab',
      fragrance: 'Neon Sugar',
      notes: ['caramel', 'synthetic musk'],
      rating: 2,
      agentComment: '',
      userComment: 'Too sweet',
      isOwned: false,
      isTried: true,
      isLiked: false,
      isDisliked: true,
      isRecommendation: false,
      season: null,
      timeOfDay: null,
      gender: null,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
  ],
  owned: [
    {
      id: 5,
      fragranceId: 5,
      brand: 'Oryxel Editions',
      fragrance: 'Noir Papyrus',
      notes: ['papyrus', 'black tea', 'ink'],
      rating: 4,
      agentComment: '',
      userComment: 'Collection',
      isOwned: true,
      isTried: true,
      isLiked: true,
      isDisliked: false,
      isRecommendation: false,
      season: null,
      timeOfDay: null,
      gender: null,
      pyramidTop: null,
      pyramidMid: null,
      pyramidBase: null,
    },
  ],
}
